### [POST] login 
POST http://localhost:3000/login HTTP/1.1
content-type: application/json

{
    "nickname": "user5",
    "password": "password5",
    "score": 3500
}

### [GET] score board
GET http://localhost:3000/score-board HTTP/1.1
content-type: application/json

### [GET] my ranking
GET http://localhost:3000/my-ranking/user1 HTTP/1.1
content-type: application/json

### [GET] my ranking
GET http://localhost:3000/my-ranking/user0 HTTP/1.1
content-type: application/json