### [POST] login 
POST http://localhost:3000/login HTTP/1.1
content-type: application/json

{
    "nickname": "user3",
    "password": "password3",
    "score": 2500
}

### [GET] score board
GET http://localhost:3000/score-board HTTP/1.1
content-type: application/json

### [GET] my ranking
GET http://localhost:3000/my-ranking?nickname=asdfasdfa HTTP/1.1
content-type: application/json

### [GET] my ranking
GET http://localhost:3000/my-ranking?nickname=user0 HTTP/1.1
content-type: application/json